services:
  migrate:
    image: ${CONTAINER_REGISTRY:-pandoraacr.azurecr.io}/ams-migration-asset:${IMAGE_TAG:-latest}
    build: .
    environment:
      - AZURE_CLIENT_ID
      - AZURE_TENANT_ID
      - AZURE_CLIENT_SECRET
      - SERVICEBUS_NAMESPACE
      - SERVICEBUS_QUEUE
